version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
    ports:
     - "3306:3306"
    restart: always

  dbadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dbadmin
    depends_on:
      - mariadb
    links:
      - mariadb:db
    restart: always

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    depends_on:
      - dbadmin
    links:
      - dbadmin
    restart: always

