version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
    ports:
     - "3306:3306"
    restart: always

  dbadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dbadmin
    depends_on:
      - mariadb
    links:
      - mariadb:db
    restart: always

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    depends_on:
      - dbadmin
      - mongo_express
    links:
      - dbadmin
      - mongo_express
    restart: always
    
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongo:/data/db
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
    restart: always

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: yourexpresspassword
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: yourmongorootpassword
    depends_on:
      - mongo
    links:
      - mongo:mongo
    restart: always

